[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# External
actix-web = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
