[workspace]
members = ["src/gateway","src/integration-tests"]
resolver = "2"

[workspace.dependencies]
# Local
gateway = { path = "src/gateway" }

# External
actix-web = "4"
anyhow = "1"
reqwest = "0.11"
serde = "1"
serde_json = "1"
serde_path_to_error = "0.1"
thiserror = "1"
tokio = "1"
